### ISSUE TITLE
Errors when running tests in docker container

### ISSUE THREAD

**Issue by prmac** [snz20/carnelian#1]
Running `python basictest_carnelian.py` in the snazeen/carnelian docker container results in the following output to stderr

```
.................EEEE..EE.......

======================================================================
ERROR: test18_train (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 204, in test18_train
    v = train(config.ftest_dir, config.model_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 706, in train
    os.rename(curr_model, model_prefix + "_final.model")
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test19_train_precise (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 219, in test19_train_precise
    v = train(config.ftest_dir, config.model_precise_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 706, in train
    os.rename(curr_model, model_prefix + "_final.model")
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test20_predict (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 232, in test20_predict
    label_file = predict(config.model_dir, config.ftest_dir, config.predict_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 926, in predict
    p.map(predict_unpack, arglist)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
RuntimeError: Could not find final model file in: /usr/local/src/carnelian/tests/demo_data/model

======================================================================
ERROR: test21_predict_precise (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 239, in test21_predict_precise
    label_file = predict(config.model_precise_dir, config.ftest_dir, config.predict_precise_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 926, in predict
    p.map(predict_unpack, arglist)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
RuntimeError: Could not find final model file in: /usr/local/src/carnelian/tests/demo_data/model_precise

======================================================================
ERROR: test23_retrain (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 259, in test23_retrain
    v = retrain(config.model_dir, config.new_model_dir, config.new_examples_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 851, in retrain
    os.rename(curr_model, model_prefix + "_final.model")
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test24_retrain_precise (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 274, in test24_retrain_precise
    v = retrain(config.model_precise_dir, config.new_model_precise_dir, config.new_examples_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 851, in retrain
    os.rename(curr_model, model_prefix + "_final.model")
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 32 tests in 0.418s

FAILED (errors=6)
```

**Comment by snz20** [comment]
Can you remove the current docker image and do a fresh run? Can you check if vowpal wabbit works in your docker container (run: vw --version)? It seems fine at my end.

**Comment by prmac** [comment]
Thanks, removed and pulled docker image.  Problem persists, vw --version returns 8.1.1

**Comment by prmac** [comment]
Looking over the output written to stdout, the following training step appears to fail with a memory error.  Can you recommend how to fix this?

```
Training using Carnelian + vowpal-wabbit
2019-05-01 15:18:27

frag_length = 16
coverage:          0.1
k-mer length:   8
row weight:      4
num hashes:      1
num batches:    1
num passes:      1
------------------------------------------------
Fasta input:    /carnelian/tests/demo_data/frag_test/small.fasta
labels input:   /carnelian/tests/demo_data/frag_test/small.label
------------------------------------------------
Number labels:  5
calling fasta2skm for batch 0
Getting training set ...
Shuffling training set ...
['vw', '--random_seed', '43', '-f', '/carnelian/tests/demo_data/model_precise/vw-model_batch-0.model', '--cache_file', '/carnelian/tests/demo_data/model_precise/train.batch-0.cache', '--passes', '1', '--save_resume', '--loss_function=logistic', '--probabilities', '--oaa', '5', '--bit_precision', '31', '--l1', '0.0', '--l2', '0.0']
('final_regressor = /carnelian/tests/demo_data/model_precise/vw-model_batch-0.model\nNum weight bits = 31\nlearning rate = 0.5\ninitial_t = 0\npower_t = 0.5\ninternal error: memory allocation failed; dying!vw (memory.h:15): internal error: memory allocation failed; dying!\n', None)
1

```

**Comment by snz20** [comment]
Try removing the "model" "model-precise" "new_model" directories from "/carnelian/tests/demo_data/" and running the tests again please as follows. Let me know if you get errors.

python basictest_carnelian.py TestCarnelian_Basic.test18_train
python basictest_carnelian.py TestCarnelian_Basic.test19_train_precise

It appears from this one and the previous outputs that vowpal-wabbit (a third party tool we use) isn't somehow running properly (I want to make sure though if that's the case). Test 20, 21, 23, and 24 failed because test 18, 19 did not run successfully to completion.

**Comment by prmac** [comment]
Thanks for getting back to me so quickly.  I've pasted the output below.

`python basictest_carnelian.py TestCarnelian_Basic.test18_train`
```
================================================
Training using Carnelian + vowpal-wabbit
2019-05-02 09:48:13

frag_length = 16
coverage:	   0.1
k-mer length:   8
row weight:	 4
num hashes:	 1
num batches:	1
num passes:	 1
------------------------------------------------
Fasta input:	/usr/local/src/carnelian/tests/demo_data/frag_test/small.fasta
labels input:   /usr/local/src/carnelian/tests/demo_data/frag_test/small.label
------------------------------------------------
Number labels:  5
calling fasta2skm for batch 0
Getting training set ...
Shuffling training set ...
['vw', '--random_seed', '43', '-f', '/usr/local/src/carnelian/tests/demo_data/model/vw-model_batch-0.model', '--cache_file', '/usr/local/src/carnelian/tests/demo_data/model/train.batch-0.cache', '--passes', '1', '--save_resume', '--oaa', '5', '--bit_precision', '31', '--l1', '0.0', '--l2', '0.0']
('final_regressor = /usr/local/src/carnelian/tests/demo_data/model/vw-model_batch-0.model\nNum weight bits = 31\nlearning rate = 0.5\ninitial_t = 0\npower_t = 0.5\ninternal error: memory allocation failed; dying!vw (memory.h:15): internal error: memory allocation failed; dying!\n', None)
E
======================================================================
ERROR: test18_train (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 204, in test18_train
    v = train(config.ftest_dir, config.model_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 706, in train
    os.rename(curr_model, model_prefix + "_final.model")
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 1 test in 0.029s

FAILED (errors=1)
```

`root@6a2fad324272:/usr/local/src/carnelian/tests# python basictest_carnelian.py TestCarnelian_Basic.test19_train_precise`
```
================================================
Training using Carnelian + vowpal-wabbit
2019-05-02 09:48:16

frag_length = 16
coverage:	   0.1
k-mer length:   8
row weight:	 4
num hashes:	 1
num batches:	1
num passes:	 1
------------------------------------------------
Fasta input:	/usr/local/src/carnelian/tests/demo_data/frag_test/small.fasta
labels input:   /usr/local/src/carnelian/tests/demo_data/frag_test/small.label
------------------------------------------------
Number labels:  5
calling fasta2skm for batch 0
Getting training set ...
Shuffling training set ...
['vw', '--random_seed', '43', '-f', '/usr/local/src/carnelian/tests/demo_data/model_precise/vw-model_batch-0.model', '--cache_file', '/usr/local/src/carnelian/tests/demo_data/model_precise/train.batch-0.cache', '--passes', '1', '--save_resume', '--loss_function=logistic', '--probabilities', '--oaa', '5', '--bit_precision', '31', '--l1', '0.0', '--l2', '0.0']
('final_regressor = /usr/local/src/carnelian/tests/demo_data/model_precise/vw-model_batch-0.model\nNum weight bits = 31\nlearning rate = 0.5\ninitial_t = 0\npower_t = 0.5\ninternal error: memory allocation failed; dying!vw (memory.h:15): internal error: memory allocation failed; dying!\n', None)
E
======================================================================
ERROR: test19_train_precise (__main__.TestCarnelian_Basic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basictest_carnelian.py", line 219, in test19_train_precise
    v = train(config.ftest_dir, config.model_precise_dir, args)
  File "/usr/local/src/carnelian/carnelian.py", line 706, in train
    os.rename(curr_model, model_prefix + "_final.model")
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (errors=1)
```

**Comment by snz20** [comment]
It does seem vowpal wabbit is not working for you. On what platform are you running the docker, please? The container seems to work for me on both macOS and unix servers.

**Comment by prmac** [comment]
I'm running Ubuntu 18.04.

**Comment by prmac** [comment]
OK, it's working on my Mac.  Must be an issue with my Linux system.  Thought Docker was supposed
to solve this sort of thing!

**Comment by snz20** [comment]
I thought so too! Glad it worked.

**Comment by prmac** [comment]
Quick update, can run carnelian in Docker container under Ubuntu 18.04 if reduce -b parameter of vw to 21.

**Comment by snz20** [comment]
Thanks for the update.
